"""E2E.1 — Machine-read prior infarct vs self-reported heart attack. UNADJUDICATED.

One supplementary row for the unrecognized-findings table, and nothing more. The
standing decision (PROJECT_CONTEXT, decision 2) is that this is not a paper, not
a primary outcome, and not a headline: AI-READI's ECG interpretations are
generated by the recording device and have not been read by a physician. Every
record in this release carries an explicit "Unconfirmed Diagnosis" stamp — all
2,251 of them, which this runner reports rather than assumes.

**The word "unadjudicated" belongs on every number that leaves this file,
figures included.** A machine-read old infarct is a statement about a waveform
pattern, not a diagnosis, and the difference matters more here than anywhere else
in the paper because the finding is exactly the kind that reads as dramatic.

Two design choices worth stating:

* **Certainty tiers are kept separate, not pooled.** The device hedges: bare
  "Inferior infarct, old" is a different claim from "Consider anterior infarct".
  Collapsing them would inflate the count with the device's own uncertainty, so
  each tier is reported and the headline uses the unhedged tier.
* **Old and age-indeterminate patterns only.** An acute or recent pattern is not
  a *prior* infarct that someone might not know about; it is a current event, and
  including it would answer a different question.

The comparator is `mhoccur_mi` ("has a doctor ever told you that you had a heart
attack"), which is the precise item. The broader kidney/heart composite used for
Aim 1 is reported alongside, because someone who reports "other heart issues"
without reporting an MI is not cleanly unaware.
"""

from __future__ import annotations

import pandas as pd

from aireadi import azure_io, constants, omop, results, stats

import _phase2

_phase2.banner("E2E.1", "Machine-read prior infarct vs self-report — UNADJUDICATED")

df = _phase2.load()

ECG = azure_io.repo_root() / "data" / "processed" / "p1" / "ecg_statements.parquet"
if not ECG.exists():
    raise SystemExit(f"missing {ECG} — run build_ecg_statements.py first")

ecg = pd.read_parquet(ECG)
ecg["person_id"] = ecg["person_id"].astype(str)
print(f"ECG interpretations: {len(ecg):,} participants, "
      f"{int(ecg.unconfirmed_stamp.sum()):,} carrying an explicit unconfirmed stamp "
      f"({100 * ecg.unconfirmed_stamp.mean():.1f}%), "
      f"{int(ecg.had_repeat_ecg.sum())} who had a repeat ECG (first kept)")

low = ecg["statements"].str.lower()
infarct = low.str.contains("infarct", na=False)
hedged = low.str.contains("consider", na=False) | low.str.contains("probable", na=False)
acute = low.str.contains("acute", na=False) | low.str.contains("recent", na=False)

# Tier assignment. A participant with several statements can match more than one
# pattern; the tier is taken from the strongest unhedged prior-infarct statement,
# so hedging cannot upgrade a claim.
def tier(statements: str) -> str:
    if not isinstance(statements, str) or "infarct" not in statements.lower():
        return "none"
    parts = [s.strip() for s in statements.split("|")]
    prior = [s for s in parts if "infarct" in s.lower()
             and "acute" not in s.lower() and "recent" not in s.lower()]
    if not prior:
        return "acute or recent only"
    if any("consider" not in s.lower() and "probable" not in s.lower() for s in prior):
        return "definite prior infarct"
    if any("probable" in s.lower() for s in prior):
        return "probable prior infarct"
    return "consider prior infarct"


ecg["infarct_tier"] = ecg["statements"].map(tier)
tiers = (ecg["infarct_tier"].value_counts().rename("n_participants")
         .to_frame().rename_axis("tier"))
tiers["pct_of_ecg_cohort"] = (100 * tiers["n_participants"] / len(ecg)).round(2)
_phase2.print_table(tiers, title="Machine-read infarct statements by certainty tier (UNADJUDICATED)")

# The precise self-report comparator, plus the composite Aim 1 uses.
obs = omop.add_item_key(azure_io.load_table(
    "observation", usecols=["person_id", "observation_source_value", "value_as_number"]))
sr_mi = omop.first_value(obs, "mhoccur_mi", name="sr_mi")
merged = (df.merge(ecg[["person_id", "infarct_tier", "unconfirmed_stamp"]],
                   on="person_id", how="inner")
            .merge(sr_mi.reset_index().assign(person_id=lambda d: d.person_id.astype(str)),
                   on="person_id", how="left"))
merged["sr_mi"] = merged["sr_mi"].where(merged["sr_mi"].isin([0, 1]))

merged["prior_infarct"] = merged["infarct_tier"].isin(
    ["definite prior infarct"]).astype(float)
merged["prior_infarct_incl_hedged"] = merged["infarct_tier"].isin(
    ["definite prior infarct", "probable prior infarct", "consider prior infarct"]
).astype(float)

rows = []
for pattern_label, pattern_col in [
    ("Definite machine-read prior infarct", "prior_infarct"),
    ("Definite + hedged (probable/consider)", "prior_infarct_incl_hedged"),
]:
    for sr_label, sr_col in [("Self-reported heart attack (mhoccur_mi)", "sr_mi"),
                             ("Self-reported any heart condition (Aim 1 composite)", "sr_heart")]:
        eligible = merged[merged[pattern_col].eq(1) & merged[sr_col].notna()]
        never_told = eligible[eligible[sr_col].eq(0)]
        got = stats.proportion(eligible[sr_col].eq(0).astype(float))
        rows.append({
            "ecg_pattern": pattern_label, "self_report": sr_label,
            "n_with_pattern": int(merged[pattern_col].sum()),
            "n_eligible": got["n"], "n_never_told": got["k"],
            "pct_unrecognized": round(got["pct"], 1),
            "ci_lo": round(got["ci_lo"], 1), "ci_hi": round(got["ci_hi"], 1),
        })
unrecognized = pd.DataFrame(rows).set_index(["ecg_pattern", "self_report"])
_phase2.print_table(unrecognized,
                    title="Machine-read prior infarct with no corresponding self-report (UNADJUDICATED)")

# Cross-tabulation, the honest full picture rather than one fraction.
cross = pd.crosstab(merged["prior_infarct"].map({0.0: "no pattern", 1.0: "prior infarct"}),
                    merged["sr_mi"].map({0.0: "no reported MI", 1.0: "reported MI"}),
                    dropna=False)
_phase2.print_table(cross, title="Machine read vs self-report, 2x2 (UNADJUDICATED)")

# Does the machine pattern agree with the biochemical marker? A machine-read old
# infarct with a normal troponin is a waveform finding, not evidence of injury.
by_tier = (merged.groupby("infarct_tier", observed=True)
                 .agg(n=("person_id", "size"), pct_troponin_abnormal=("abn_heart", "mean"),
                      median_troponin=("troponin_t", "median"))
                 .assign(pct_troponin_abnormal=lambda d: (100 * d.pct_troponin_abnormal).round(1))
                 .round(2))
_phase2.print_table(by_tier, title="Troponin by machine-read tier — does the pattern co-travel with injury?")

headline = unrecognized.loc[("Definite machine-read prior infarct",
                             "Self-reported heart attack (mhoccur_mi)")]

results.save(
    "E2E.1", unrecognized, paper="p1",
    method=("UNADJUDICATED, MACHINE-GENERATED, PHYSICIAN-UNREVIEWED. Machine-read prior "
            "infarct statements harvested from the WFDB .hea headers "
            "(build_ecg_statements.py) against same-day self-reported heart attack. "
            "Certainty tiers kept separate rather than pooled; acute/recent patterns "
            "excluded, since those are not PRIOR infarcts. Repeat ECGs deduplicated to the "
            "first record. Reported as one supplementary row, never a headline "
            "(PROJECT_CONTEXT decision 2)."),
    result=(f"UNADJUDICATED. All {int(ecg.unconfirmed_stamp.sum()):,} of {len(ecg):,} ECG "
            f"records carry an explicit unconfirmed-diagnosis stamp. "
            f"{int(merged.prior_infarct.sum())} participants have an unhedged machine-read "
            f"prior-infarct pattern; of the {int(headline.n_eligible)} who also answered the "
            f"heart-attack item, {int(headline.n_never_told)} "
            f"({headline.pct_unrecognized}%, 95% CI {headline.ci_lo}-{headline.ci_hi}) "
            f"reported no heart attack. Including hedged statements raises the pattern count "
            f"to {int(merged.prior_infarct_incl_hedged.sum())}. Tier counts: "
            + "; ".join(f"{t} {int(r.n_participants)}" for t, r in tiers.iterrows())
            + ". This is a waveform-pattern statement, not a diagnosis, and must be labelled "
              "unadjudicated everywhere it appears including figures."),
    decision="keep", name="unrecognized",
)
results.save(
    "E2E.1", tiers, paper="p1",
    method="Machine-read infarct statement counts by certainty tier (UNADJUDICATED).",
    result="; ".join(f"{t}: {int(r.n_participants)} ({r.pct_of_ecg_cohort}%)"
                     for t, r in tiers.iterrows()),
    decision="keep", name="tiers", primary=False,
)
results.save(
    "E2E.1", by_tier, paper="p1",
    method=("Troponin abnormality rate and median by machine-read infarct tier, checking "
            "whether the ECG pattern co-travels with biochemical injury (UNADJUDICATED)."),
    result="; ".join(f"{t}: n={int(r.n)}, {r.pct_troponin_abnormal}% troponin-abnormal, "
                     f"median {r.median_troponin} ng/L" for t, r in by_tier.iterrows()),
    decision="keep", name="by_tier", primary=False,
)
